server:
  servlet:
    context-path: /app4share
  port: 9999

app:
  uri: http://localhost:${server.port}/${server.servlet.context-path}
  auth:
    jwt:
      secret: vk+mpseqHqhOYSD/3QJBku823lgmrZn/YEJgFoOJuPy+Kouy7HsuTPJMv/8Iu6N1
    users: adminuser
  ipa:
    upload-path: files/ipa
  apk:
    upload-path: files/apk

spring:
  profiles:
    active:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:file:./h2-db
    username:
    password:
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
